Repository DEPthes/3rd-MVP-Overload-Server, pull requests merged in 2024-07, with the labels that each got.

#2 [FEAT]: 로그인 / 회원가입
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/mvp/deplog/domain/TestController.java
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/domain/respository/RefreshTokenRepository.java
  src/main/java/mvp/deplog/domain/auth/dto/JoinReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginRes.java
  src/main/java/mvp/deplog/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/common/BaseEntity.java
  src/main/java/mvp/deplog/domain/common/Status.java
  src/main/java/mvp/deplog/domain/user/domain/Part.java
  src/main/java/mvp/deplog/domain/user/domain/Role.java
  src/main/java/mvp/deplog/domain/user/domain/User.java
  src/main/java/mvp/deplog/domain/user/domain/repository/UserRepository.java
  src/main/java/mvp/deplog/global/config/JpaConfig.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/security/UserDetailsImpl.java
  src/main/java/mvp/deplog/global/security/UserDetailsServiceImpl.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/resources/application.yml
Labels: :rainbow: 기능

#5 [FEAT]: 엔티티 설정
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/mvp/deplog/domain/TestController.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/domain/respository/RefreshTokenRepository.java
  src/main/java/mvp/deplog/domain/auth/dto/JoinReq.java
  src/main/java/mvp/deplog/domain/block/domain/Block.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/common/BaseEntity.java
  src/main/java/mvp/deplog/domain/likes/domain/Likes.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/member/domain/Part.java
  src/main/java/mvp/deplog/domain/member/domain/Role.java
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/Stage.java
  src/main/java/mvp/deplog/domain/scrap/domain/Scrap.java
  src/main/java/mvp/deplog/domain/tag/domain/Tag.java
  src/main/java/mvp/deplog/domain/tagging/Tagging.java
  src/main/java/mvp/deplog/domain/user/domain/User.java
  src/main/java/mvp/deplog/domain/user/domain/repository/UserRepository.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/security/UserDetailsImpl.java
  src/main/java/mvp/deplog/global/security/UserDetailsServiceImpl.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
Labels: :rainbow: 기능

#8 [FEAT]: db 버전 관리 / 응답 형식 통일 / 예외 처리
  build.gradle
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/dto/JoinReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/block/domain/Block.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/likes/domain/Likes.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/scrap/domain/Scrap.java
  src/main/java/mvp/deplog/domain/tag/domain/Tag.java
  src/main/java/mvp/deplog/domain/tagging/Tagging.java
  src/main/java/mvp/deplog/global/common/Message.java
  src/main/java/mvp/deplog/global/common/SuccessResponse.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/exception/BusinessException.java
  src/main/java/mvp/deplog/global/exception/ErrorCode.java
  src/main/java/mvp/deplog/global/exception/ErrorResponse.java
  src/main/java/mvp/deplog/global/exception/GlobalExceptionHandler.java
  src/main/java/mvp/deplog/global/security/AuthenticationEntryPointImpl.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
Labels: :rainbow: 기능, 🛠️ 리팩토링

#9 V.1.0.0 Deploy
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/mvp/deplog/domain/TestController.java
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/domain/respository/RefreshTokenRepository.java
  src/main/java/mvp/deplog/domain/auth/dto/JoinReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginReq.java
  src/main/java/mvp/deplog/domain/auth/dto/LoginRes.java
  src/main/java/mvp/deplog/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/block/domain/Block.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/common/BaseEntity.java
  src/main/java/mvp/deplog/domain/common/Status.java
  src/main/java/mvp/deplog/domain/likes/domain/Likes.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/member/domain/Part.java
  src/main/java/mvp/deplog/domain/member/domain/Role.java
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/Stage.java
  src/main/java/mvp/deplog/domain/scrap/domain/Scrap.java
  src/main/java/mvp/deplog/domain/tag/domain/Tag.java
  src/main/java/mvp/deplog/domain/tagging/Tagging.java
  src/main/java/mvp/deplog/global/common/Message.java
  src/main/java/mvp/deplog/global/common/SuccessResponse.java
  src/main/java/mvp/deplog/global/config/JpaConfig.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/config/SwaggerConfig.java
  src/main/java/mvp/deplog/global/exception/BusinessException.java
  src/main/java/mvp/deplog/global/exception/ErrorCode.java
  src/main/java/mvp/deplog/global/exception/ErrorResponse.java
  src/main/java/mvp/deplog/global/exception/GlobalExceptionHandler.java
  src/main/java/mvp/deplog/global/security/AuthenticationEntryPointImpl.java
  src/main/java/mvp/deplog/global/security/UserDetailsImpl.java
  src/main/java/mvp/deplog/global/security/UserDetailsServiceImpl.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/resources/application-swagger.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
Labels: :earth_americas: 인프라, 🔖버전

#10 V.1.0.0 Deploy
  .github/workflows/cicd.yml
Labels: :earth_americas: 인프라, 🔖버전

#7 Feat/#6 write post
  .github/workflows/cicd.yml
  src/main/java/mvp/deplog/domain/block/domain/repository/BlockRepository.java
  src/main/java/mvp/deplog/domain/block/dto/BlockReq.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/PostReq.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/tag/domain/repository/TagRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :rainbow: 기능

#14 [FEAT]: block 테이블 삭제 / post 테이블 컬럼 추가 + 스웨거 에러 응답 추가
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/block/domain/Block.java
  src/main/java/mvp/deplog/domain/block/domain/repository/BlockRepository.java
  src/main/java/mvp/deplog/domain/block/dto/BlockReq.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/dto/PostReq.java
  src/main/resources/db/migration/V2__remove_block_modify_post.sql
Labels: :rainbow: 기능, 🛠️ 리팩토링
