Repository DEPthes/3rd-MVP-Overload-Server, pull requests merged in 2024-08, with the labels that each got.

#16 [REFACTOR]: block 삭제로 인한 게시글 작성 로직 변경
  build.gradle
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/request/JoinReq.java
  src/main/java/mvp/deplog/domain/auth/dto/request/LoginReq.java
  src/main/java/mvp/deplog/domain/auth/dto/response/LoginRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/dto/PostReq.java
  src/main/java/mvp/deplog/domain/post/dto/request/PostReq.java
  src/main/java/mvp/deplog/domain/post/dto/response/CreatePostRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/infrastructure/MarkdownUtil.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#19 [FEAT]: 이메일 중복 체크 API 구현
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/response/EmailDuplicateCheckRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#21 [REFACTOR]: 예외 처리 추가 (IllegalArgumentException, ArrayIndexOutOfBoundsException)
  src/main/java/mvp/deplog/global/exception/GlobalExceptionHandler.java
Labels: 🛠️ 리팩토링

#18 [FEAT]: 댓글 작성 API 구현
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
Labels: :bug: 버그, :rainbow: 기능

#23 [FEAT]: 이메일 인증 과정을 통한 회원가입
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/exception/ErrorCode.java
  src/main/java/mvp/deplog/global/exception/GlobalExceptionHandler.java
  src/main/java/mvp/deplog/infrastructure/mail/MailConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/MailUtil.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/dto/MailCodeRes.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
  src/main/java/mvp/deplog/infrastructure/markdown/MarkdownUtil.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisConfig.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisUtil.java
  src/main/resources/application.yml
  src/main/resources/templates/verification-email.html
Labels: :earth_americas: 인프라, :rainbow: 기능

#24 V.2.0.0 Deploy
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/request/JoinReq.java
  src/main/java/mvp/deplog/domain/auth/dto/request/LoginReq.java
  src/main/java/mvp/deplog/domain/auth/dto/response/EmailDuplicateCheckRes.java
  src/main/java/mvp/deplog/domain/auth/dto/response/LoginRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/block/domain/Block.java
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/PostReq.java
  src/main/java/mvp/deplog/domain/post/dto/response/CreatePostRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/tag/domain/repository/TagRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/exception/ErrorCode.java
  src/main/java/mvp/deplog/global/exception/GlobalExceptionHandler.java
  src/main/java/mvp/deplog/infrastructure/mail/MailConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/MailUtil.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/dto/MailCodeRes.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
  src/main/java/mvp/deplog/infrastructure/markdown/MarkdownUtil.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisConfig.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisUtil.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__remove_block_modify_post.sql
  src/main/resources/templates/verification-email.html
Labels: :earth_americas: 인프라, 🔖버전

#26 [FEAT]: 비밀번호 변경 API 구현
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/request/ModifyPasswordReq.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
Labels: :bug: 버그, :rainbow: 기능

#32 [FEAT]: 내 정보 조회 API 구현
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/member/application/MemberService.java
  src/main/java/mvp/deplog/domain/member/application/MemberServiceImpl.java
  src/main/java/mvp/deplog/domain/member/dto/response/MyInfoRes.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberApi.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
Labels: :rainbow: 기능

#27 [FEAT]: 게시글 목록 조회 API 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/PostListReq.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostListRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/global/common/PageInfo.java
  src/main/java/mvp/deplog/global/common/PageResponse.java
  src/main/resources/application.yml
Labels: :rainbow: 기능

#33 [FEAT]: 이미지 저장을 위한 S3 설정
  build.gradle
  src/main/java/mvp/deplog/infrastructure/s3/S3Config.java
  src/main/java/mvp/deplog/infrastructure/s3/S3FileUtil.java
  src/main/java/mvp/deplog/infrastructure/s3/application/FileService.java
  src/main/java/mvp/deplog/infrastructure/s3/application/S3FileServiceImpl.java
Labels: :earth_americas: 인프라, :rainbow: 기능

#35 [FEAT]: Mapstruct 도입
  build.gradle
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/mapper/MemberAuthMapper.java
  src/main/java/mvp/deplog/domain/auth/dto/request/JoinReq.java
  src/main/java/mvp/deplog/domain/member/application/MemberServiceImpl.java
  src/main/java/mvp/deplog/domain/member/dto/mapper/MemberMapper.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#37 [FEAT]: 게시글 스크랩 API 구현
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/scrap/application/ScrapService.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapApi.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapController.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#38 [FEAT]: 아바타 이미지 업로드 API 구현
  build.gradle
  src/main/java/mvp/deplog/domain/member/application/MemberService.java
  src/main/java/mvp/deplog/domain/member/application/MemberServiceImpl.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberApi.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
  src/main/java/mvp/deplog/infrastructure/s3/S3FileUtil.java
  src/main/java/mvp/deplog/infrastructure/s3/application/S3FileServiceImpl.java
Labels: :rainbow: 기능

#43 [FEAT]: 게시글 작성 중 이미지 업로드 URL 반환
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/infrastructure/s3/dto/response/FileUrlRes.java
Labels: :rainbow: 기능

#41 [FEAT]: 게시글 스크랩 해제 API 구현
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/scrap/application/ScrapService.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapApi.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapController.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#46 [FEAT]: 게시글 좋아요 및 좋아요 해제 API
  src/main/java/mvp/deplog/domain/likes/application/LikesService.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/likes/presentation/LikesApi.java
  src/main/java/mvp/deplog/domain/likes/presentation/LikesController.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#47 [FEAT}: 게시글 상세 조회 API 구현
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/CreatePostReq.java
  src/main/java/mvp/deplog/domain/post/dto/request/PostListReq.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostDetailsRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostListRes.java
  src/main/java/mvp/deplog/domain/post/exception/ResourceNotFoundException.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapApi.java
  src/main/java/mvp/deplog/domain/tag/domain/repository/TagRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :rainbow: 기능

#51 [FEAT]: 게시글 검색 API 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
Labels: :bug: 버그, :rainbow: 기능

#53 [FEAT]: 스크랩 게시글 목록 조회 API 구현
  src/main/java/mvp/deplog/domain/scrap/application/ScrapService.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapApi.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapController.java
Labels: :rainbow: 기능

#55 [FEAT}: 태그로 게시글 검색 API 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/tag/domain/repository/TagRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :rainbow: 기능

#58 [FEAT]: 게시글 삭제 API 구현
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/exception/UnauthorizedException.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :rainbow: 기능

#60 [FEAT}: 임시 저장 게시글 API 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
Labels: :rainbow: 기능

#66 [FEAT]: 회원/비회원 구분
  src/main/java/mvp/deplog/domain/TestController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailServiceFactory.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/dto/response/AnonymousPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/MemberPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#68 [FEAT}: 임시저장 게시글 목록 조회 API 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/response/TempListRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
Labels: :rainbow: 기능

#69 [REFACTOR]: 토큰 저장소 변경
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/domain/respository/RefreshTokenRepository.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisConfig.java
  src/main/resources/db/migration/V3__remove_refresh_token.sql
Labels: :earth_americas: 인프라, :rainbow: 기능, 🛠️ 리팩토링

#72 [FEAT]: 게시글 수정 API 구현
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#74 V.2.2.0 Deploy
  src/main/java/mvp/deplog/domain/TestController.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/domain/RefreshToken.java
  src/main/java/mvp/deplog/domain/auth/domain/respository/RefreshTokenRepository.java
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/ReplyListRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/likes/application/LikesService.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/likes/presentation/LikesApi.java
  src/main/java/mvp/deplog/domain/likes/presentation/LikesController.java
  src/main/java/mvp/deplog/domain/member/domain/repository/MemberRepository.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailService.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailServiceFactory.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/CreatePostReq.java
  src/main/java/mvp/deplog/domain/post/dto/request/PostListReq.java
  src/main/java/mvp/deplog/domain/post/dto/response/AnonymousPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/MemberPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostListRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/TempListRes.java
  src/main/java/mvp/deplog/domain/post/exception/ResourceNotFoundException.java
  src/main/java/mvp/deplog/domain/post/exception/UnauthorizedException.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/scrap/application/ScrapService.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapApi.java
  src/main/java/mvp/deplog/domain/scrap/presentation/ScrapController.java
  src/main/java/mvp/deplog/domain/tag/domain/repository/TagRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/java/mvp/deplog/infrastructure/redis/RedisConfig.java
  src/main/java/mvp/deplog/infrastructure/s3/dto/response/FileUrlRes.java
  src/main/resources/db/migration/V3__remove_refresh_token.sql
Labels: 🛠️ 리팩토링, 🔖버전

#76 [FIX]: 댓글 작성 및 조회 시 아바타 이미지 관리 방식 수정
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/ReplyListRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailServiceFactory.java
  src/main/java/mvp/deplog/global/config/SwaggerConfig.java
  src/main/resources/db/migration/V4__modify_comment_avatar.sql
Labels: :bug: 버그, :earth_americas: 인프라

#63 [REFACTOR]: 임시 저장 게시글 조회 제외 구현
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :bug: 버그, 🛠️ 리팩토링

#78 [FEAT]: 토큰 재발급 API 구현
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/response/ReissueRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
Labels: :rainbow: 기능

#79 [FEAT]: 로그아웃 API
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/request/LogoutReq.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
Labels: :rainbow: 기능

#81 [FEAT]: 프론트 로컬 cors 설정
  src/main/java/mvp/deplog/global/config/WebMvcConfig.java
Labels: :earth_americas: 인프라, :rainbow: 기능

#82 V.2.2.1 Deploy
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/dto/request/LogoutReq.java
  src/main/java/mvp/deplog/domain/auth/dto/response/ReissueRes.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/ReplyListRes.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/PostDetailServiceFactory.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
  src/main/java/mvp/deplog/global/config/SwaggerConfig.java
  src/main/java/mvp/deplog/global/config/WebMvcConfig.java
  src/main/java/mvp/deplog/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProvider.java
  src/main/java/mvp/deplog/global/security/jwt/JwtTokenProviderImpl.java
  src/main/resources/db/migration/V4__modify_comment_avatar.sql
Labels: 🛠️ 리팩토링, 🔖버전

#87 [REFACTOR]: 이메일 인증 시 타임리프 디자인 개선
  build.gradle
  src/main/java/mvp/deplog/global/config/SecurityConfig.java
  src/main/java/mvp/deplog/global/config/WebMvcConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
  src/main/resources/application.yml
  src/main/resources/static/images/deplog-airplane.png
  src/main/resources/templates/fail.html
  src/main/resources/templates/success.html
  src/main/resources/templates/verification-email.html
Labels: 🛠️ 리팩토링

#88 [REFACTPR]: 아바타 저장 방식 수정 및 그에 따른 로직 수정
  src/main/java/mvp/deplog/domain/member/WriterInfo.java
  src/main/java/mvp/deplog/domain/member/application/MemberService.java
  src/main/java/mvp/deplog/domain/member/application/MemberServiceImpl.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/member/dto/Avatar.java
  src/main/java/mvp/deplog/domain/member/dto/mapper/MemberMapper.java
  src/main/java/mvp/deplog/domain/member/dto/request/ModifyAvatarReq.java
  src/main/java/mvp/deplog/domain/member/dto/response/MyInfoRes.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberApi.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/dto/response/AnonymousPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/MemberPostDetailRes.java
  src/main/resources/db/migration/V5__modift_member_avatar.sql
Labels: 🛠️ 리팩토링

#91 V.3.0.0 Deploy
  build.gradle
  src/main/java/mvp/deplog/domain/member/WriterInfo.java
  src/main/java/mvp/deplog/domain/member/application/MemberService.java
  src/main/java/mvp/deplog/domain/member/application/MemberServiceImpl.java
  src/main/java/mvp/deplog/domain/member/domain/Member.java
  src/main/java/mvp/deplog/domain/member/dto/Avatar.java
  src/main/java/mvp/deplog/domain/member/dto/mapper/MemberMapper.java
  src/main/java/mvp/deplog/domain/member/dto/request/ModifyAvatarReq.java
  src/main/java/mvp/deplog/domain/member/dto/response/MyInfoRes.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberApi.java
  src/main/java/mvp/deplog/domain/member/presentation/MemberController.java
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/dto/response/AnonymousPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/dto/response/MemberPostDetailRes.java
  src/main/java/mvp/deplog/global/config/WebMvcConfig.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V5__modift_member_avatar.sql
  src/main/resources/static/images/deplog-airplane.png
  src/main/resources/templates/fail.html
  src/main/resources/templates/success.html
  src/main/resources/templates/verification-email.html
Labels: :earth_americas: 인프라, 🛠️ 리팩토링, 🔖버전

#92 [REFACTOR]: post 검색용 content 컬럼 추가 + ddl 작성
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/resources/db/migration/V6__add_post_search_content.sql
Labels: 🛠️ 리팩토링

#93 V.3.1.0 Deploy
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/resources/db/migration/V6__add_post_search_content.sql
Labels: 🔖버전

#96 [FIX]: 회원 - 댓글 연결
  src/main/java/mvp/deplog/domain/comment/application/CreateAnonymousCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateAnonymousReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/resources/db/migration/V7__add_fk_comment_member.sql
Labels: :bug: 버그, 🛠️ 리팩토링

#97 V.3.2.0 Deploy
  src/main/java/mvp/deplog/domain/comment/application/CreateAnonymousCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateAnonymousReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateCommentServiceFactory.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/resources/db/migration/V7__add_fk_comment_member.sql
Labels: 🔖버전

#98 [REFACTOR]: 댓글 조회 시 체크박스 여부에 따른 아바타 이미지 관련 로직 수정
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/ReplyListRes.java
  src/main/resources/db/migration/V8__remove_comment_avatar.sql
Labels: :earth_americas: 인프라, 🛠️ 리팩토링

#99 V.4.0.0 Deploy
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberCommentServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/application/CreateMemberReplyServiceImpl.java
  src/main/java/mvp/deplog/domain/comment/domain/Comment.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/dto/response/CommentListRes.java
  src/main/java/mvp/deplog/domain/comment/dto/response/ReplyListRes.java
  src/main/resources/db/migration/V8__remove_comment_avatar.sql
Labels: 🛠️ 리팩토링, 🔖버전

#101 [FEAT]: 비밀번호 재설정 시 메일 인증 여부 확인 api
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/dto/MailVerifyRes.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
Labels: :rainbow: 기능

#102 V.4.1.0 Deploy
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
  src/main/java/mvp/deplog/infrastructure/mail/application/MailService.java
  src/main/java/mvp/deplog/infrastructure/mail/dto/MailVerifyRes.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailApi.java
  src/main/java/mvp/deplog/infrastructure/mail/presentation/MailController.java
Labels: 🔖버전

#103 [REFACTOR]: 게시글 관련 로직 수정
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/CreatePostReq.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
Labels: 🛠️ 리팩토링

#105 [REFACTOR]: 댓글 관련 로직 수정
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
Labels: 🛠️ 리팩토링

#106 [FEAT]: 회원 탈퇴 API 및 게시글 상세 조회 null 체크
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: :bug: 버그, :rainbow: 기능

#107 V.4.1.1 Deploy
  src/main/java/mvp/deplog/domain/auth/application/AuthService.java
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthApi.java
  src/main/java/mvp/deplog/domain/auth/presentation/AuthController.java
  src/main/java/mvp/deplog/domain/comment/application/CommentService.java
  src/main/java/mvp/deplog/domain/comment/domain/repository/CommentRepository.java
  src/main/java/mvp/deplog/domain/comment/dto/request/CreateCommentReq.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentApi.java
  src/main/java/mvp/deplog/domain/comment/presentation/CommentController.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/Post.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/request/CreatePostReq.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/mvp/deplog/domain/tagging/repository/TaggingRepository.java
Labels: 🔖버전

#109 [FEAT]: 임시저장 게시글 상세 조회 API
  src/main/java/mvp/deplog/domain/post/application/AnonymousPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/MemberPostDetailServiceImpl.java
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/domain/repository/PostRepository.java
  src/main/java/mvp/deplog/domain/post/dto/response/TempPostDetailRes.java
  src/main/java/mvp/deplog/domain/post/presentation/PostApi.java
  src/main/java/mvp/deplog/domain/post/presentation/PostController.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#110 [REFACTOR]: 메일 인증 디자인 개선
  src/main/resources/static/images/deplog-airplane.png
  src/main/resources/static/images/deplog_logo.png
  src/main/resources/static/images/fail_animal.png
  src/main/resources/static/images/success_animal.png
  src/main/resources/templates/fail.html
  src/main/resources/templates/success.html
  src/main/resources/templates/verification-email.html
Labels: 🛠️ 리팩토링

#113 [REFACTOR]: 게시글 목록 조회 시 아바타 추가
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostListRes.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#114 V.4.2.1 Deploy
  src/main/java/mvp/deplog/domain/post/application/PostService.java
  src/main/java/mvp/deplog/domain/post/dto/response/PostListRes.java
  src/main/java/mvp/deplog/global/security/SecurityConfig.java
Labels: 🔖버전

#118 V.4.2.3 Deploy && [FIX]: 회원 탈퇴 시 탈퇴 회원이 작성한 게시글 스크랩 및 좋아요 삭제
  src/main/java/mvp/deplog/domain/auth/application/AuthServiceImpl.java
  src/main/java/mvp/deplog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/mvp/deplog/domain/scrap/domain/repository/ScrapRepository.java
Labels: :bug: 버그, 🔖버전

#120 V.4.2.4 Deploy && [FIX]: 게시글 미리보기 개행 적용
  src/main/java/mvp/deplog/infrastructure/markdown/MarkdownUtil.java
Labels: :bug: 버그, 🔖버전

#121 V.4.2.5 Deploy && [REFACTOR]: 회원 가입 시 승인 대기 상태로 지정
  src/main/java/mvp/deplog/domain/member/domain/Member.java
Labels: 🛠️ 리팩토링, 🔖버전
